name: covidapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  equatable: ^1.1.1
  firebase_core: ^0.3.4
  firebase_auth: ^0.8.4+2
  http: 0.12.0+2
  rxdart: ^0.23.1
  json_annotation: ^3.0.0
  flutter_svg: ^0.17.3+1
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  country_code_picker: ^1.3.7
  gender_picker: ^1.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.8.0
  json_serializable: ^3.2.3
  hive_generator: ^0.7.0+2


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lang/es.json
    - assets/logo.svg
    - assets/images/coronavirus.svg
    - assets/images/coronavirus-bottom.svg
    - assets/images/woman.svg
    - assets/images/man.svg
    - assets/images/man.png
    - assets/images/wallpaper-home.jpg
    - assets/images/world.svg
    - assets/images/person.svg
    - assets/images/infected.svg
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Futura
      fonts:
        - asset: assets/fonts/FuturaStd-Book.otf
        - asset: assets/fonts/FuturaStd-Heavy.otf
          weight: 300
        - asset: assets/fonts/FuturaStd-Bold.ttf
          weight: 600
    - family: Avalon
      fonts:
        - asset: assets/fonts/Avalon.ttf
        - asset: assets/fonts/AvalonBold.ttf
          weight: 600
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
